### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by encukou** [stejsle1/lab03#1]
- [x] Javu v ČR/SR používá podstatně méně respondentů než 299 (a ostatní odpovědi kolem Javy jsou taky vedle). Zkontroluj si prosím kód.

- [x] Podle grafu je průměrná mzda programátorů v Clojure 0 (čeho?). Je to rozumný výsledek?

**Comment by stejsle1** [comment]
Ahoj, 
diky za kontrolu.

1.  u Javy jsem matchovala i JavaScript... lze matchovat substring nejak inteligentneji nez spojit dva pripady (kdy je 'Java' na konci stringu a kdy je 'Java;' uprostred seznamu jazyku)?
2. jazyky "bez mzdy" jsem vyhodila a presunula do seznamu pod graf

**Comment by encukou** [comment]
> lze matchovat substring nejak inteligentneji nez spojit dva pripady (kdy je 'Java' na konci stringu a kdy je 'Java;' uprostred seznamu jazyku)?

Jistě, lze – už tam vidím nějaký regulární výraz, v tom by mělo jít zapsat dvě možnosti.
Ale ani není potřeba "matchovat substring"; kód pro ten graf to taky nedělá.
